trigger:
  - develop
  - test
  - uat
  - main

parameters:
  - name: CommitHash
    type: string
    default: ''

stages:
# ─────────────── BUILD & VALIDATION ─────────────── 
- stage: BuildAndValidate
  displayName: "Build & Pre-Deploy Validation"
  jobs:
  - job: DeployToSalesforce
    displayName: "Deploy to Non-Prod Orgs"
    condition: always()
    pool:
      vmImage: 'ubuntu-latest'

    variables:
      - ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
            - group: obsglobal--sfdev
      - ${{ if eq(variables['Build.SourceBranchName'], 'test') }}:
            - group: obsglobal--sftest
      - ${{ if eq(variables['Build.SourceBranchName'], 'uat') }}:
            - group: obsglobal--sfuat
      - ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
            - group: obsglobal--sfprod-predeployment
            
      - name: system.debug
        value: true

      - name: commitHashParam
        value: ${{parameters.CommitHash}}

    steps:
      - checkout: self
        persistCredentials: true
        fetchDepth: 0
        displayName: "Checkout repository"

      - template: templates/install-sf-cli.yml

      - template: templates/get-commit-hash.yml
        parameters:
          commitHashParam: $(commitHashParam)

      - template: templates/get-last-successful-commit.yml
        parameters:
          commitHashVariable: $(commitHash)

      - template: templates/install-plugin.yml 

      - template: templates/generate-delta.yml
        parameters:
          commit_hash: $(commitHash)   

      - task: Bash@3
        inputs:
          targetType: "inline"
          script: |
            echo "Generating sf command for running tests..."
            # Run the Node.js script
            sfCommandTests=$(node -e "require('./pipelines/GenerateSfdxCommand.js')();") 

            # Set the Azure DevOps pipeline variable
            echo "##vso[task.setvariable variable=sfCommandTests]$sfCommandTests"
            echo "sfCommandTests: $sfCommandTests"
        displayName: "Generate sf command for running tests"

      - template: templates/sf-login.yml
        parameters:
          sf_username: $(SF_USERNAME)
          sf_password: $(SF_PASSWORD)
          sf_client_id: $(SF_CLIENT_ID)
          sf_client_secret: $(SF_CLIENT_SECRET)
          sf_login_url: $(SF_LOGIN_URL)

      - template: templates/sf-check-deploy.yml
        parameters:
          includeSfCommandTests: true
          displayName: "Check to deploy to Salesforce"

      - template: templates/sf-check-deploy.yml
        parameters:
          runAllTests: true
          displayName: "Run all tests"

      - task: Bash@3
        condition: and(succeeded(), ne(variables['Build.SourceBranchName'], 'main'))
        inputs:
          targetType: "inline"
          script: |
            echo "Deploying to Salesforce..."

            echo "Searching for the directory containing sfdx-project.json..."

            # Find the directory containing sfdx-project.json
            sfdx_project_dir=$(find . -name 'sfdx-project.json' -exec dirname {} \; | head -n 1)

            if [ -z "$sfdx_project_dir" ]; then
              echo "sfdx-project.json not found!"
              exit 1
            fi

            echo "Found sfdx-project.json in directory: $sfdx_project_dir"

            # Move to the directory containing sfdx-project.json
            cd "$sfdx_project_dir"

            sf project deploy start -x ./delta/package/package.xml --post-destructive-changes ./delta/destructiveChanges/destructiveChanges.xml --test-level RunLocalTests --verbose --json --target-org $(SF_INSTANCE_NAME)

        displayName: "Deploy to Salesforce"

# ─────────────── PRODUCTION DEPLOYMENT ───────────────
- stage: DeployToProd
  displayName: "Deploy to Salesforce PROD"
  dependsOn: BuildAndValidate
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'main'))

  variables:
    - group: obsglobal--sfprod  # Approval is only required for this group

  jobs:
    - job: DeployToProdJob
      displayName: "Deploy to PROD"
      pool:
        vmImage: 'ubuntu-latest'

      steps:
        - checkout: self
          persistCredentials: true
          fetchDepth: 0

        - template: templates/install-sf-cli.yml

        - template: templates/get-last-successful-commit.yml
          parameters:
            commitHashVariable: $(commitHash)

        - template: templates/install-plugin.yml

        - template: templates/generate-delta.yml
          parameters:
            commit_hash: $(commitHash)

        - template: templates/sf-login.yml
          parameters:
            sf_username: $(SF_USERNAME)
            sf_password: $(SF_PASSWORD)
            sf_client_id: $(SF_CLIENT_ID)
            sf_client_secret: $(SF_CLIENT_SECRET)
            sf_login_url: $(SF_LOGIN_URL)

        - task: Bash@3
          inputs:
            targetType: "inline"
            script: |
              echo "Deploying to PROD..."
              sfdx_project_dir=$(find . -name 'sfdx-project.json' -exec dirname {} \; | head -n 1)
              cd "$sfdx_project_dir"
              sf project deploy start -x ./delta/package/package.xml --post-destructive-changes ./delta/destructiveChanges/destructiveChanges.xml --test-level RunLocalTests --verbose --json --target-org $(SF_INSTANCE_NAME)
          displayName: "Deploy to Salesforce PROD"
